# In-Class Programming Activity, Day 3

## Márcio Porto

## Task 1

```{r}
library("ISLR", lib.loc="~/R/library")
data(College, package = "ISLR")
```

## Task 2

```{r}
College$Yield = College$Enroll / College$Accept
```

## Task 3

```{r}
all_indices <- seq(from = 1L, to = nrow(College))
train_indices <- sample(all_indices, size=200, replace=FALSE)
test_indices <- setdiff(all_indices, train_indices)
Train_data <- College[train_indices,]
Test_data <- College[test_indices,]
```

## Task 4

```{r}
Yield_mod1 <- lm(Yield ~ Top10perc + Outstate + Expend, data=Train_data)
```

## Task 5

```{r}
Y_train <- Train_data$Yield
fhat_train <- predict(Yield_mod1, newdata = Train_data)
MSE_train <- mean((Y_train - fhat_train)^2)
```

## Task 6

```{r}
Yield_mod2 <- lm(Yield ~ Top10perc + Outstate + Expend, data=Test_data)

Y_test <- Test_data$Yield
fhat_test <- predict(Yield_mod2, newdata = Test_data)
MSE_test = mean((Y_test - fhat_test)^2)
```

## Test statements

```{r}
scoreActivity::score253(3)
```






