# In-Class Programming Activity, Day 8

## Márcio Porto

## Task 1

### 1.

```{r}
x <- runif(100, 20, 70)
y <- 5 + 3*x + 2*rnorm(100)
My_data <- data.frame(x, y)
```

### 2.

```{r}
plot(x, y)
```

### 3.

```{r}
LL_line <- function(params){
  sum(log(dnorm(y - (params[1] * x + params[2]), sd = params[3])))
}
```

### 4.

```{r}
testA <- LL_line(c(3, 5, 2))
testA <- LL_line(c(4, 1, 10))
```

### 5.

```{r}
starting_params <- c(4, 1, 10)
best <- optim(starting_params, LL_line, control=list(fnscale = -1))
```

## Task 2

```{r}
load(url("http://tiny.cc/dcf/Taxi_trips.rda"))

taxi_likelihood <- function(params, data=Taxi_trips) {
  base_fare <- params[1]
  per_mile <- params[2]
  rate <- 1/params[3]
  excess <- with(data, fare_amount - (base_fare + per_mile * trip_distance))
  sum(log(dexp(excess, rate) + 1e-5))
}

starting_params <- c(2.0, 4.0, 0.5)
best <- optim(starting_params, taxi_likelihood, control=list(fnscale = -1), data=Taxi_trips)
plot(fare_amount ~ trip_distance, data=Taxi_trips)
abline(best$par[1], best$par[2], col="red")
```



## Test statements

```{r}
scoreActivity::score253(8)
```