# In-Class Programming Activity, Day 9

## Marcio Porto

```{r}
poker_deck = c(outer((10 * 2:14), 1:4, '+')) 

suits = function(x) {
  x %% 10
}

ranks = function(x) {
  x %/% 10
}

is_royal_flush = function(hand) {
  all(ranks(hand) == 13:9) && all(diff(suits(hand)) == 0)
}

is_straight_flush = function(hand) {
    all(diff(sort(ranks(hand))) == 1) && all(ranks(hand) != 13:9) && all(diff(suits(hand))== 0) 
}

is_four_of_a_kind = function(hand) {
  rank_freq = table(ranks(hand))
  return(max(rank_freq) == 4)
}

is_full_house = function(hand) {
  rank_freq = table(ranks(hand))
  return((max(rank_freq) == 3) && (min(rank_freq) == 2))
}

is_flush = function(hand) {
  suit_freq = table(suits(hand))
  return(max(suit_freq) == 5)
}

is_straight = function(hand) {
   all(diff(sort(ranks(hand))) == 1)
}

is_three_of_a_kind = function(hand) {
  rank_freq = table(ranks(hand))
  return((max(rank_freq) == 3) && (min(rank_freq) == 1))
}

is_two_pair = function(hand) {
  hand_rank = sort(ranks(hand))
  rank_freq = table(hand_rank)
  return(length(rank_freq[rank_freq == 2]) == 2)
}

is_pair = function(hand) {
  hand_rank = sort(ranks(hand))
  rank_freq = table(hand_rank)
  return(length(rank_freq[rank_freq == 2]) == 1)
}

before_draw = function(x) {
  five_cards = sample(poker_deck, 5)
  if (is_royal_flush(five_cards)) {  
    return("You have a: Royal flush")
  } else if (is_straight_flush(five_cards)) {
    return("You have a: Straight flush")
  } else if (is_full_house(five_cards)) {
    return("You have a: Full house")
  } else if (is_straight(five_cards)) {
    return("You have a: Straight")
  } else if (is_flush(five_cards)) {
    return("You have a: Flush")
  } else if (is_four_of_a_kind(five_cards)) {
    return("You have a: Four of a kind")
  } else if (is_three_of_a_kind(five_cards)) {
    return("You have a: Three of a kind")
  } else if (is_two_pair(five_cards)) {
    return("You have a: Two pairs")
  } else if (is_pair(five_cards)) {
    return("You have a: One pair")
  } else {
    return("Nothing!")
  }
}

table(sapply(1:10000, FUN=before_draw))
```


## Test statements

```{r}
scoreActivity::score253(9)
```
