# In-Class Programming Activity, Day 16

## Márcio Porto

## The knots
 
```{r}
my_knots = function(x, k) {
  return(as.vector(quantile(x, 1:(k-1) / k)))
}
```

## The basis set

```{r}
spline_model_matrix = function(x, knot_locations) {
  MM = cbind(1, x, x^2, x^3)
  for (i in knot_locations) {
    MM = cbind(MM, ((x - i) ^ 3)(x < i))
  }
  return(MM)
}
```

## Finding the best linear combination

```{r}
fit_spline = function(formula, k=2, data=parent.frame()) {
  y = eval(formula[[2]], envir=data)
  x = eval(formula[[3]], envir=data)
  knot_locations = my_knots(x, k)
  MM = spline_model_matrix(x, knot_locations)
  mod = lm(y ~ MM - 1)
  res = list(coef = coef(mod), knots = knot_locations, cov = vcov(mod))
  class(res) = "my_spline"

  return(res)
}
```

## The predict function

```{r}
predict.my_spline = function(mod, newx, level = 0.95,
           intervals=c("none", "confidence", "prediction")) {
  intervals = match.arg(intervals)
  MM = spline_model_matrix(newx, mod$knots)
  vals = MM %*% mod$coef
  se = sqrt(rowSums(MM %*% mod$cov * MM))
  if (intervals == "none") return(vals)
  else return(NULL) # for future use
}
```

## Confidence intervals

## Prediction intervals

## How many knots?

## Test statements

```{r}
scoreActivity::score253(16)
```
