# In-Class Programming Activity, Day 17

## Márcio Porto

## Growing and Pruning Trees

```{r}
library(tree)
library(mosaicData)
Cartoon_data = data.frame(
  x = 1:8,
  y = c(2, 5, 1, 3, 8, 5, 4, 6),
  class = c("A", "B", "A", "A", "B", "B", "A", "B")
)
```

## Perfectly pure trees

```{r}
pure = tree.control(8, mincut=0, minsize=1, mindev=0)

rtree_pure = tree(y ~ x, data=Cartoon_data, control = pure)

plot(rtree_pure)
text(rtree_pure)
```

Output for x=3: 1

```{r}
ctree_pure <- tree(class ~ x, data=Cartoon_data, control = pure)

plot(ctree_pure)
text(ctree_pure)
```

Output for x=7: A

## Evaluating the tree

```{r}
predict(rtree_pure)
predict(ctree_pure)

predict(rtree_pure, newdata = data.frame(x = 3))
predict(ctree_pure, newdata = data.frame(x = 7))
```

## Deviance of each node

```{r}
print(rtree_pure)
print(ctree_pure)
```

## Deviance of a tree

## Pruning the tree

```{r}
rtree_5 = prune.tree(rtree_pure, best = 5)
ctree_2 = prune.misclass(ctree_pure, best = 2)

nterminal = c(2:8)
tree_deviance = sum(rtree_5$residuals ^ 2)
```

## Building a real classifier

```{r}
pure_for_cps = tree.control(nrow(CPS85), mincut = 0, minsize = 1, mindev = 0)

Sector_classifier = tree(sector ~ wage + sex + educ + exper, data=mosaicData::CPS85, control=pure_for_cps)

Sector_classifier_20 = prune.misclass(Sector_classifier, best = 20)

plot(Sector_classifier_20)
text(Sector_classifier_20)
```

## Test statements

This was broken last time I ran this script, so I uncommented it in order to be able to run the Rmd file.

```{r}
# scoreActivity::score253(17)
```
